services:
  - type: web
    name: yougile-sync-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main_web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: YOUGILE_API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PG_SCHEMA
        value: public
      - key: HEADLESS
        value: "1"
