services:
  - type: web
    name: yougile-sync-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main_web.py
    envVars:
      - key: YOUGILE_API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PG_SCHEMA
        value: public
      - key: HEADLESS
        value: "1"

  - type: worker
    name: yougile-sync-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main_worker.py
    envVars:
      - key: YOUGILE_API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PG_SCHEMA
        value: public
      - key: WORKER_MODE
        value: loop
      - key: SYNC_INTERVAL_SEC
        value: "900"

jobs:
  - name: yougile-sync-cron
    schedule: "0 * * * *"
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main_worker.py
    envVars:
      - key: YOUGILE_API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PG_SCHEMA
        value: public
      - key: WORKER_MODE
        value: once
